### ISSUE TITLE
Undeclared identifier uint

### ISSUE THREAD

**Issue by mruegenberg** [frauzufall/ofxSortableList#2]
Hi,
I'm on Windows and I get `error C2065: 'uint': undeclared identifier` in Visual Studio.

The solution is to add the following at the top of `ofxSortableList.cpp`:

```
#ifndef uint
#define uint unsigned int
#endif
```

**Comment by frauzufall** [comment]
Hey, thanks for testing! https://github.com/frauzufall/ofxSortableList/commit/baaab35b6446b0d37408ed4c1d2c81d6b7ff67a4 should fix this, just update your repository. I also renamed the examples (others on windows had problems with `-` in the example name).
